version: "3.6"

networks:
  splunknet:
    driver: bridge
    attachable: true

services:
  so1:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    hostname: so1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD
      - DEBUG=true
      - JAVA_VERSION=openjdk:8
    ports:
      - 8000
      - 8089
      