version: "3.1"

networks:
  splunknet:
    driver: overlay 

services:
  so1:
    networks:
      splunknet:
        aliases:
          - so1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    hostname: so1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_LICENSE_URI=/run/secrets/splunk_license
      - SPLUNK_PASSWORD
    ports:
      - 8000
      - 8089
    secrets:
      - splunk_license
      
secrets:
    splunk_license:
        external: true
