version: "3.6"

networks:
  splunknet:
    driver: bridge
    attachable: true

services:
  site1_sh1:
    networks:
      splunknet:
        aliases:
          - site1_sh1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: site1_sh1
    container_name: site1_sh1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=site1_idx1,site1_idx2
      - SPLUNK_SEARCH_HEAD_URL=site1_sh1,site1_sh2
      - SPLUNK_CLUSTER_MASTER_URL=site1_cm1
      - SPLUNK_ROLE=splunk_search_head
      - SPLUNK_LICENSE_URI
      - DEBUG=true
      - SPLUNK_PASSWORD
      - SPLUNK_SITE=site1
      - SPLUNK_MULTISITE_MASTER=site1_cm1
      - SPLUNK_SHC_SECRET=F00bar1234!
      - SPLUNK_IDXC_SECRET=F00bar1234!
    ports:
      - 8000
      - 8089
      
  site1_sh2:
    networks:
      splunknet:
        aliases:
          - site1_sh2
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: site1_sh2
    container_name: site1_sh2
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=site1_idx1,site1_idx2
      - SPLUNK_SEARCH_HEAD_URL=site1_sh1,site1_sh2
      - SPLUNK_CLUSTER_MASTER_URL=site1_cm1
      - SPLUNK_ROLE=splunk_search_head
      - SPLUNK_LICENSE_URI
      - DEBUG=true
      - SPLUNK_PASSWORD
      - SPLUNK_SITE=site1
      - SPLUNK_MULTISITE_MASTER=site1_cm1
      - SPLUNK_SHC_SECRET=F00bar1234!
      - SPLUNK_IDXC_SECRET=F00bar1234!
    ports:
      - 8000
      - 8089

  site1_cm1:
    networks:
      splunknet:
        aliases:
          - site1_cm1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: site1_cm1
    container_name: site1_cm1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=site1_idx1,site1_idx2
      - SPLUNK_SEARCH_HEAD_URL=site1_sh1,site1_sh2
      - SPLUNK_CLUSTER_MASTER_URL=site1_cm1
      - SPLUNK_ROLE=splunk_cluster_master
      - SPLUNK_LICENSE_URI
      - DEBUG=true
      - SPLUNK_PASSWORD
      - SPLUNK_SITE=site1
      - SPLUNK_ALL_SITES=site1,site2
      - SPLUNK_MULTISITE_MASTER=site1_cm1
      - SPLUNK_MULTISITE_REPLICATION_FACTOR_ORIGIN=1
      - SPLUNK_MULTISITE_REPLICATION_FACTOR_TOTAL=1
      - SPLUNK_MULTISITE_SEARCH_FACTOR_ORIGIN=1
      - SPLUNK_MULTISITE_SEARCH_FACTOR_TOTAL=1
      - SPLUNK_SHC_SECRET=F00bar1234!
      - SPLUNK_IDXC_SECRET=F00bar1234!
    ports:
      - 8000
      - 8089

  site1_idx1:
    networks:
      splunknet:
        aliases:
          - site1_idx1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: site1_idx1
    container_name: site1_idx1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=site1_idx1,site1_idx2
      - SPLUNK_SEARCH_HEAD_URL=site1_sh1,site1_sh2
      - SPLUNK_CLUSTER_MASTER_URL=site1_cm1
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_LICENSE_URI
      - DEBUG=true
      - SPLUNK_PASSWORD
      - SPLUNK_SITE=site1
      - SPLUNK_MULTISITE_MASTER=site1_cm1
      - SPLUNK_SHC_SECRET=F00bar1234!
      - SPLUNK_IDXC_SECRET=F00bar1234!
    ports:
      - 8000
      - 8089

  site1_idx2:
    networks:
      splunknet:
        aliases:
          - site1_idx2
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: site1_idx2
    container_name: site1_idx2
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=site1_idx1,site1_idx2
      - SPLUNK_SEARCH_HEAD_URL=site1_sh1,site1_sh2
      - SPLUNK_CLUSTER_MASTER_URL=site1_cm1
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_LICENSE_URI
      - DEBUG=true
      - SPLUNK_PASSWORD
      - SPLUNK_SITE=site1
      - SPLUNK_MULTISITE_MASTER=site1_cm1
      - SPLUNK_SHC_SECRET=F00bar1234!
      - SPLUNK_IDXC_SECRET=F00bar1234!
    ports:
      - 8000
      - 8089

  site2_sh1:
    networks:
      splunknet:
        aliases:
          - site2_sh1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: site2_sh1
    container_name: site2_sh1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=site2_idx1,site2_idx2
      - SPLUNK_SEARCH_HEAD_URL=site2_sh1,site2_sh2
      - SPLUNK_CLUSTER_MASTER_URL=site2_cm1
      - SPLUNK_ROLE=splunk_search_head
      - SPLUNK_LICENSE_URI
      - DEBUG=true
      - SPLUNK_PASSWORD
      - SPLUNK_SITE=site2
      - SPLUNK_MULTISITE_MASTER=site1_cm1
      - SPLUNK_SHC_SECRET=F00bar1234!
      - SPLUNK_IDXC_SECRET=F00bar1234!
    ports:
      - 8000
      - 8089

# Second site    

  site2_sh2:
    networks:
      splunknet:
        aliases:
          - site2_sh2
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: site2_sh2
    container_name: site2_sh2
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=site2_idx1,site2_idx2
      - SPLUNK_SEARCH_HEAD_URL=site2_sh1,site2_sh2
      - SPLUNK_CLUSTER_MASTER_URL=site2_cm1
      - SPLUNK_ROLE=splunk_search_head
      - SPLUNK_LICENSE_URI
      - DEBUG=true
      - SPLUNK_PASSWORD
      - SPLUNK_SITE=site2
      - SPLUNK_MULTISITE_MASTER=site1_cm1
      - SPLUNK_SHC_SECRET=F00bar1234!
      - SPLUNK_IDXC_SECRET=F00bar1234!
    ports:
      - 8000
      - 8089

  site2_cm1:
    networks:
      splunknet:
        aliases:
          - site2_cm1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: site2_cm1
    container_name: site2_cm1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=site2_idx1,site2_idx2
      - SPLUNK_SEARCH_HEAD_URL=site2_sh1,site2_sh2
      - SPLUNK_CLUSTER_MASTER_URL=site2_cm1
      - SPLUNK_ROLE=splunk_cluster_master
      - SPLUNK_LICENSE_URI
      - DEBUG=true
      - SPLUNK_PASSWORD
      #These are unused, but useful in case you want to change the cluster master site
      - SPLUNK_SITE=site2
      - SPLUNK_ALL_SITES=site1,site2
      - SPLUNK_MULTISITE_MASTER=site1_cm1
      - SPLUNK_MULTISITE_REPLICATION_FACTOR_ORIGIN=1
      - SPLUNK_MULTISITE_REPLICATION_FACTOR_TOTAL=1
      - SPLUNK_MULTISITE_SEARCH_FACTOR_ORIGIN=1
      - SPLUNK_MULTISITE_SEARCH_FACTOR_TOTAL=1
      - SPLUNK_SHC_SECRET=F00bar1234!
      - SPLUNK_IDXC_SECRET=F00bar1234!
      #Note that we don't need SPLUNK_SITE, SPLUNK_MULTISITE_MASTER here
    ports:
      - 8000
      - 8089

  site2_idx1:
    networks:
      splunknet:
        aliases:
          - site2_idx1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: site2_idx1
    container_name: site2_idx1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=site2_idx1,site2_idx2
      - SPLUNK_SEARCH_HEAD_URL=site2_sh1,site2_sh2
      - SPLUNK_CLUSTER_MASTER_URL=site2_cm1
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_LICENSE_URI
      - DEBUG=true
      - SPLUNK_PASSWORD
      - SPLUNK_SITE=site2
      - SPLUNK_MULTISITE_MASTER=site1_cm1
      - SPLUNK_SHC_SECRET=F00bar1234!
      - SPLUNK_IDXC_SECRET=F00bar1234!
    ports:
      - 8000
      - 8089

  site2_idx2:
    networks:
      splunknet:
        aliases:
          - site2_idx2
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: site2_idx2
    container_name: site2_idx2
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=site2_idx1,site2_idx2
      - SPLUNK_SEARCH_HEAD_URL=site2_sh1,site2_sh2
      - SPLUNK_CLUSTER_MASTER_URL=site2_cm1
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_LICENSE_URI
      - DEBUG=true
      - SPLUNK_PASSWORD
      - SPLUNK_SITE=site2
      - SPLUNK_MULTISITE_MASTER=site1_cm1
      - SPLUNK_SHC_SECRET=F00bar1234!
      - SPLUNK_IDXC_SECRET=F00bar1234!
    ports:
      - 8000
      - 8089
