---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-deployer-data
  labels:
    app: splunk
    role: splunk_deployer
    tier: management
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-deployer-config
  labels:
    app: splunk
    role: splunk_deployer
    tier: management
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

