---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-search-data
  labels:
    app: splunk
    role: splunk_search_head
    tier: search
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-search-config
  labels:
    app: splunk
    role: splunk_search_head
    tier: search
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

